[package]
name = "dt"
version = "0.1.0"
authors = ["Yuan Liu <yuan6liu@gmail.com>"]
edition = "2018"

[dependencies]
ndarray = "0.13.1"
ndarray-rand = "0.11.0"
num = "0.3"

[dev-dependencies]
lodepng = "2.6.0"
rgb = "0.8"


